name: Retrain Model on Tag Push
on:
  push:
    tags:
      - 'v*'

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deployment/requirements.txt
      - name: Run training script
        run: python pipeline/train_model.py
      - name: Save model artifact
        uses: actions/upload-artifact@v4
        with:
          name: xgboost_model
          path: models/xgboost_final_model.joblib
